### ISSUE TITLE
FEATURE REQUEST: Add MMR/Win/Loss

### ISSUE THREAD

**Issue by vytarien** [ubelhj/OBSCounter#1]
I saw in "Update 3" that "I don't plan on adding any mmr or win streak stuff, as there's a couple plugins that support that already for OBS." (JerryTheBee, BakkesPlugins.com)

However, I have reasons to state that those plugins are not as good. The one that is most recommended, RocketStats, does not work as well as this one does. Furthermore, the developer of RocketStats is not the best with English (for months, it was "Loses" not "Losses"). I have found many bugs for it over the course of a couple of days.

I have not found others with win/loss features like this one, and I have reasons to believe that it'll surpass RocketStats, and others, in functionality.

Whether you decide to/against this feature request, please advise.

Sincerely,
Cylizion
Owner of Natrix Uprising, LLC
E: [redacted]

**Comment by ubelhj** [comment]
I really appreciate the support. I already have wins and losses in the plugin, so I have some of this implemented. I could add win or loss streaks reasonably easily, and will look into that when I get some free time. MMR is just a bit of a big request to work on, and would work completely differently than the rest of the plugin. MMR is a whole different project in my opinion, and with 2 working projects that already exist I don't have much motivation to do so. If there's an issue with another person's plugin, let them know on discord. All of us love hearing feedback and I'm sure it would be welcomed.
